#!/usr/bin/env bash
# Installs nginx and configures a new Ubuntu machine

sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/indexs.html
sudo service nginx start
