#!/usr/bin/env bash
# Resolve localhost to 127.0.0.2
# Resolve fb to 8.8.8.8

sudo cp "/etc/hosts" "$HOME/hosts.new"
echo "127.0.0.2 \tlocalhost" > "$HOME/hosts.new"
echo "8.8.8.8 \tfacebook.com" >> "$HOME/hosts.new"
sudo cp -f "$HOME/hosts.new" "/etc/hosts"
